### ISSUE TITLE
Find more accurate way to get path for "get_pid.sh"

### ISSUE THREAD

**Issue by bmhagui** [bmhagui/stage_52#13]
On french based machines, the file cannot be found automatically.

**Comment by rudametw** [comment]
What does "French based machines" mean ? Why are they any different ?

**Comment by bmhagui** [comment]
When getting the path I used used the word "File" with grep  and on my laptop I have a French version of Ubuntu and it didn't work because in this one it say Fichier, for my stat commamd. I had to copy the file manually.
