### ISSUE TITLE
Blacklist records PID, what happens after closing and reopening the app ?

### ISSUE THREAD

**Issue by rudametw** [bmhagui/stage_52#7]
If the application's PID changes, you must ensure that the blacklisted app stays blacklisted. For example, if I blacklist pidgin, I would expect it to continue to be blacklisted after a restart.

**Comment by bmhagui** [comment]
The bash file "get_pid.sh" is launched on every iteration of the application. So even if the application is closed and re-opened, its new PID will be obtained and stored in "black_list_pid.conf"
